import { Amplify } from 'aws-amplify';
import outputs from '@/amplify_outputs.json';

/**
 * Configures Amplify using the auto-generated amplify_outputs.json file.
 * This file is generated by:
 *   - `npx ampx sandbox` (local development)
 *   - AWS Amplify Console (CI/CD production builds)
 * No manual AWS resource IDs are needed — Gen 2 manages them automatically.
 */
export function configureAmplify() {
  Amplify.configure(outputs, { ssr: true });
}
